### ISSUE TITLE
Does it work on other phones ?

### ISSUE THREAD

**Issue by seamug** [KonradIT/goprohero#1]
Hi 

I have just tested the app on a Lenovo smartphone running android 4.4.2 connected to GoPro 3 Silver. It doesn't seemed to work. Does it only work on Nexus?

Update:  Tested on Samsung Note 2 . Connected Fine. when I tried live preview . It stream for a sec and then I got this error message (see attached). Can you advise?
![screenshot_2015-04-08-18-17-50-samsung note 2](https://cloud.githubusercontent.com/assets/4831208/7043521/b411b1ac-de1c-11e4-8979-8c5848c08ace.png)

**Comment by KonradIT** [comment]
Hi,

Will update the live preview, what is exactly happening with the lenovo phone? Minimum is JB (4.3) but dont worry, will update to make it compatible with 3.XX whatever. :)

Can you take some screenshot of the app on the N2 please?

Ninja edit: It works on: my Nexus 6 w/ chroma rom, crDroid, liquidsmooth and elementalX, leankernel, franco, so root/kernel/rom (flashacolism) is not affecting anything. Also works on my friends nexus 5 with everything stock.

**Comment by seamug** [comment]
Hi Konrad. Actually the screenshot i attached is from N2.  Lenovo also experienced the same error message.

**Comment by KonradIT** [comment]
@seamug download the latest release and try it, it fixed most things

**Comment by seamug** [comment]
Hi 

I downloaded the app from Amazon. It still showing same issue on Lenovo. Will try it on N2.. Btw, will you be updating the source code as well ?

Update : N2 works on Live View .I'm using hero 3 silver. but sometimes (between 5-10s) the message 'Can't play video' appears and I have to refresh stream.

**Comment by seamug** [comment]
Hi Any solution to my issue? Is it something to do with the player?

**Comment by KonradIT** [comment]
Hi,

Fixed in latest release

**Comment by seamug** [comment]
Hi Konrad

Thanks for the update. I tried on Samsung Note2 and although its kind of jerky , its still can stream. However more often than not, the error message 'Can't play video' still appears. Do you need ample storage on the phone to be able to stream?

Apologies for the brevity of this message
